spring:
  application:
    name: grocery
  profiles:
    active: local
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grocery
    username: root
    password: StrongP@ssw0rd!2025
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: ORCA_MINI
        temperature: 0.7
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

# JWT configuration
jwt:
  secret: wbzeYgClG0B9an2Reo0+aKpmauIHkJwsVw0SfIeqI8g=

# Swagger UI configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  packagesToScan: com.grocery

logging:
  level:
    root: INFO
    com.grocery.security: DEBUG
    com.grocery.config: WARN
    com.grocery.user: ERROR
  file:
    name: logs/grocery.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"