services:
  db:
    build: ./mysql
    container_name: mysql-container
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: StrongP@ssw0rd!2025
      MYSQL_DATABASE: grocery
      MYSQL_USER: user
      MYSQL_PASSWORD: UserP@ssw0rd!2024

volumes:
  mysql-data: